@startuml ldm
!pragma layout smetana
left to right direction
entity GiaoDich
entity CaNhan
entity ToChuc
entity NguoiThamGiaGiaodich
entity TaiSanGiaoDich

entity GiaoDich {
  * giaoDichId: int    - Mã giao dịch, tự động tăng
  * createdAt: datetime - Ngày tạo
  * updatedAt: datetime      - Ngày cập nhật

}
entity CaNhan {
  * caNhanId: int    - Mã cá nhân, tự động tăng
  * createdAt: datetime - Ngày tạo
  * updatedAt: datetime      - Ngày cập nhật
}
entity ToChuc {
  * toChucId: int - Mã tổ chức, tự động tăng
  * createdAt: datetime - Ngày tạo
  * updatedAt: datetime      - Ngày cập nhật
}
entity NguoiThamGiaGiaodich {
  * nguoiThamGiaGiaodichId: int    - Mã bản ghi, tự động tăng
  * createdAt: datetime - Ngày tạo
  * updatedAt: datetime      - Ngày cập nhật
}
entity TaiSan {
  * taiSanId: int    - Mã tài sản, tự động tăng
  * createdAt: datetime - Ngày tạo
  * updatedAt: datetime      - Ngày cập nhật
}

entity TaiSanGiaoDich {
  * taiSanGiaoDichId: int    - Mã bản ghi, tự động tăng
  * createdAt: datetime - Ngày tạo
  * updatedAt: datetime      - Ngày cập nhật
}


@enduml
