@startuml erd
!pragma layout smetana
left to right direction
entity Nguoi
entity CongChungVien
entity ChungChiHanhNghe
entity ChuKySo
entity LichSuCapNhatThongTin
entity LichSuCapNhatChuKySo
entity ToChucCongChung

CongChungVien ||..|| Nguoi
CongChungVien ||..{ ChungChiHanhNghe
CongChungVien ||..o{ ChuKySo
ToChucCongChung ||..{ CongChungVien
ChuKySo ||..{ LichSuCapNhatChuKySo
CongChungVien ||..{ LichSuCapNhatThongTin
@enduml


