@startuml erd
!pragma layout smetana
left to right direction
entity Nguoi
entity CongChungVien
entity ChungChiHanhNghe
entity ChuKySo
entity LichSuCapNhatThongtin
entity ToChucCongChung

CongChungVien ||..|| Nguoi
CongChungVien ||..{ ChungChiHanhNghe
CongChungVien ||..o{ ChuKySo
ToChucCongChung ||..{ CongChungVien
@enduml


