@startuml erd
!pragma layout smetana
left to right direction
entity GiaoDich 
entity CongChungVien 
entity ToChucCongChung
entity ChuKySo
entity Nguoi

entity LichSuHanhNghe
entity LichSuCapNhatThongtinCCV
entity LichSuCapNhatThongtinChungChi
entity LichSuCapNhatThongtinChuKySo

CongChungVien ||..{ GiaoDich
CongChungVien ||..|| Nguoi
ToChucCongChung ||..{ GiaoDich
LichSuHanhNghe }..|| CongChungVien
LichSuHanhNghe }..|| ToChucCongChung
LichSuCapNhatThongtinCCV }..|| CongChungVien
LichSuCapNhatThongtinChungChi }..|| CongChungVien
ChuKySo }..|| CongChungVien
LichSuCapNhatThongtinChuKySo }..|| ChuKySo

@enduml


