@startuml CRUD_Matrix
note as CRUD_Matrix
| Entity / Use Case        | UC_CCV_List | UC_CCV_Detail | UC_CCV_Create | UC_CCV_Update | UC_CCV_Delete | UC_CCV_Search | UC_CCV_Export | UC_CCV_History | UC_Cert_Detail | UC_Cert_History | UC_Cert_Stats | UC_Cert_Appointment | UC_Cert_Revocation | UC_Sign_List | UC_Sign_Detail | UC_Sign_Search | UC_Sign_Create | UC_Sign_Update | UC_Sign_Delete | UC_Sign_Submit | UC_Sign_ApproveReject | UC_Sign_History | UC_Search_CCV | UC_Search_Cert | UC_Search_CCV_Summary | UC_Search_CCV_Change | UC_Search_CCV_Demographics | UC_Search_CCV_Platform | UC_Search_CCV_Software |
| :----------------------- | :---------: | :-----------: | :-----------: | :-----------: | :-----------: | :-----------: | :-----------: | :------------: | :------------: | :-------------: | :-----------: | :-----------------: | :----------------: | :----------: | :------------: | :------------: | :------------: | :------------: | :------------: | :------------: | :-------------------: | :--------------: | :-----------: | :------------: | :-------------------: | :-----------------: | :-------------------------: | :--------------------: | :---------------------: |
| CongChungVien            | R           | R             | C             | U             | D             | R             | R             | R              | -              | -               | -             | -                   | -                  | -            | -              | -              | -              | -              | -              | -              | -                     | -                | R             | -              | R                     | R                   | R                           | R                      | R                       |
| ChungChiHanhNghe         | -           | R             | -             | -             | D             | -             | -             | R              | R              | R               | R             | R                   | R                  | -            | -              | -              | -              | -              | -              | -              | -                     | -                | -             | R              | -                     | -                   | -                           | -                      | -                       |
| LichSuChungChi           | -           | -             | -             | -             | -             | -             | -             | R              | R              | R               | -             | -                   | -                  | -            | -              | -              | -              | -              | -              | -              | -                     | -                | -             | -              | -                     | -                   | -                           | -                      | -                       |
| ThongTinBoNhiemMienNhiem | R           | R             | C             | U C           | D             | R             | R             | R              | -              | -               | R             | R                   | R                  | -            | -              | -              | -              | -              | -              | -              | -                     | -                | -             | -              | -                     | -                   | -                           | -                      | -                       |
| ChuKySo                  | -           | R             | -             | -             | D             | -             | -             | R              | -              | -               | -             | -                   | -                  | R            | R              | R              | C              | U              | D              | C              | R                     | R                | -             | -              | -                     | -                   | -                           | -                      | -                       |
| LichSuCapNhatThongtin    | -           | -             | C             | C             | U             | -             | -             | R              | -              | R               | -             | -                   | -                  | -            | -              | -              | -              | -              | -              | -              | -                     | R                | -             | -              | -                     | -                   | -                           | -                      | -                       |
| ToChucCongChung          | R           | R             | R             | R             | -             | R             | R             | R              | -              | -               | -             | -                   | -                  | -            | -              | -              | -              | -              | -              | -              | -                     | -                | -             | -              | -                     | -                   | -                           | -                      | -                       |

end note
@enduml
